name: Documents

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test R ${{ matrix.config.r }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - {r: '3.6.3'  }
          - {r: 'release'}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: extendr/extendr
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: extendr-api w/o graphics
        run: cargo doc --package extendr-api --no-deps

      - name: extendr-api w/o graphics w/ bindgen
        run: cargo doc --package extendr-api --no-deps --features graphics --features libR-sys/use-bindgen

      - name: extendr-api w/o graphics
        run: cargo doc --package extendr-api --no-deps --features graphics

